version: '3'
services:
  mongodb:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - ~/data:/data/db
  consul:
    image: consul
    ports:
      - 8500:8500
  bookstore-gateway:
    build: ./bookstore-gateway
    ports:
      - 8084:8084
    depends_on:
      - consul
    links:
      - consul
    environment:
      MICRONAUT_SERVICE_HOST: bookstore-gateway
      MICRONAUT_SERVICE_PORT: 8084
      CONSUL_HOST: consul
      CONSUL_PORT: 8500
  bookstore:
    build: ./bookstore
    depends_on:
      - mongodb
      - consul
    links:
      - mongodb
      - consul
    environment:
      MONGO_HOST: mongodb
      MONGO_PORT: 27017
      CONSUL_HOST: consul
      CONSUL_PORT: 8500
