micronaut:
  application:
    name: bookstore
  config-client:
    enabled: true
  server:
    host: ${MICRONAUT_SERVICE_HOST:localhost}
    port: ${MICRONAUT_SERVICE_PORT:-1}
  security:
    enabled: true
    oauth2:
      enabled: true
      clients:
        google:
          client-id: '125430829634-scgtafm4dfidecffke3rorgivdt55soq.apps.googleusercontent.com'
          client-secret: '1pnAHnzqU1129lXWYdZiglWZ'
          openid:
            issuer: 'https://accounts.google.com'
    token:
      jwt:
        enabled: true
        cookie:
          enabled: true
        signatures:
          secret:
            generator:
              secret: maryhadalittlelambherfleecewaswhiteassnow
    endpoints:
      logout:
        enabled: true
        get-allowed: true
    writer:
      header:
        enabled: true


consul:
  client:
    registration:
      enabled: true
    defaultZone: "${CONSUL_HOST:localhost}:${CONSUL_PORT:8500}"

mongodb:
  uri: "mongodb://${MG_HOST:localhost}:${MG_PORT:27017}/bookstore"
  cluster:
    maxWaitQueueSize: 5
  connectionPool:
    maxSize: 20

tracing:
  zipkin:
    enabled: true
    http:
      url: "http://${ZIPKIN_HOST:localhost}:${ZIPKIN_PORT:9411}"
      sampler:
        probability: 1.0 # Configuration taking 100% of the request to be processed by Zipkin. In a real production system, that could be overwhelming.
